/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalg57.vistas;

import finalgrupo57.AccesoADatos.AlojamientoData;
import finalgrupo57.AccesoADatos.CiudadData;
import finalgrupo57.AccesoADatos.PaqueteData;
import finalgrupo57.AccesoADatos.PasajeData;
import finalgrupo57.Entidades.Alojamiento;
import finalgrupo57.Entidades.Ciudad;
import finalgrupo57.Entidades.Paquete;
import finalgrupo57.Entidades.Pasaje;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PanelAdmin2 extends javax.swing.JPanel {

    private DefaultTableModel modelo1;
    private DefaultTableModel modelo2;
    private DefaultTableModel modelo3;
    private DefaultTableModel modelo4;
    private CiudadData cData;
    private List<Ciudad> listaC;
    private AlojamientoData aData;
    private List<Alojamiento> listaA;
    private PasajeData tData;
    private List<Pasaje> listaT;
    private PaqueteData pData;
    private List<Paquete> listaP;
    
    //paraAgregCiu
    private CiudadData ciuData = new CiudadData();
    private Ciudad ciudadnew=null;
    
    
    public PanelAdmin2() {
        initComponents();
        modelo1 = new DefaultTableModel();
        modelo2 = new DefaultTableModel();
        modelo3 = new DefaultTableModel();
        modelo4 = new DefaultTableModel();
        armarCabeceraTabla1();
        armarCabeceraTabla2();
        armarCabeceraTabla3();
        armarCabeceraTabla4();
        cData = new CiudadData();
        listaC = cData.listarCiudad();
        aData = new AlojamientoData();
        listaA= aData.listarAlojamientos();
        tData = new PasajeData();
        listaT = tData.listarPasajes();
        pData = new PaqueteData();
        listaP = pData.listarPaquetes();
        
        cargarCiudades();
        cargarAlojamientos();
        cargarTransportes();
        cargarPaquetes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCiudades = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextCiudad = new javax.swing.JTextField();
        jTextPais = new javax.swing.JTextField();
        jTextProvincia = new javax.swing.JTextField();
        jbAgregarCiu = new javax.swing.JButton();
        jbModificarCiu = new javax.swing.JButton();
        jbEliminarCiu = new javax.swing.JButton();
        jbSalirCiu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botonEstadoCiudad = new javax.swing.JRadioButton();
        jbLimpiarCiu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtAlojamientos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextCiudadAlo = new javax.swing.JTextField();
        jTextTipoAlo = new javax.swing.JTextField();
        jTextCostoAlo = new javax.swing.JTextField();
        jTextServicioAlo = new javax.swing.JTextField();
        jbAgregarAlo = new javax.swing.JButton();
        jbModificarAlo = new javax.swing.JButton();
        jbEliminarAlo = new javax.swing.JButton();
        jbSalirAlo = new javax.swing.JButton();
        jbLimpiarAlo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtTransportes = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextTipoTransp = new javax.swing.JTextField();
        jTextPrecioTransp = new javax.swing.JTextField();
        jTextCiudadOrigenTransp = new javax.swing.JTextField();
        jbAgregarTran = new javax.swing.JButton();
        jbModificarTran = new javax.swing.JButton();
        jbEliminarTran = new javax.swing.JButton();
        jbSalirTran = new javax.swing.JButton();
        jbLimpiarTran = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtPaquetes = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextCiuOrgPaq = new javax.swing.JTextField();
        jTextCiuDesPaq = new javax.swing.JTextField();
        jTextAlojamientoPaq = new javax.swing.JTextField();
        jTextTransportePaq = new javax.swing.JTextField();
        jbAgregarPaq = new javax.swing.JButton();
        jbModificarPaq = new javax.swing.JButton();
        jbEliminarPaq = new javax.swing.JButton();
        jbSalirPaq = new javax.swing.JButton();
        jbLimpiarPaq = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(10, 52, 80));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Panel Administrador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jtCiudades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Ciudad", "Pais", "Provincia", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jtCiudades);

        jLabel2.setText("Ciudad:");

        jLabel3.setText("Pais:");

        jLabel4.setText("Provincia/Estado/Region:");

        jTextCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCiudadActionPerformed(evt);
            }
        });
        jTextCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCiudadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCiudadKeyTyped(evt);
            }
        });

        jTextPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPaisActionPerformed(evt);
            }
        });
        jTextPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPaisKeyTyped(evt);
            }
        });

        jTextProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextProvinciaActionPerformed(evt);
            }
        });
        jTextProvincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextProvinciaKeyTyped(evt);
            }
        });

        jbAgregarCiu.setText("Agregar");
        jbAgregarCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarCiuActionPerformed(evt);
            }
        });

        jbModificarCiu.setText("Modificar");
        jbModificarCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarCiuActionPerformed(evt);
            }
        });

        jbEliminarCiu.setText("Eliminar");
        jbEliminarCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarCiuActionPerformed(evt);
            }
        });

        jbSalirCiu.setText("Salir");
        jbSalirCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirCiuActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado:");

        jbLimpiarCiu.setText("Limpiar");
        jbLimpiarCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarCiuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbLimpiarCiu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbAgregarCiu)
                                .addGap(113, 113, 113)
                                .addComponent(jbModificarCiu)
                                .addGap(118, 118, 118))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextPais, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(botonEstadoCiudad))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(116, 116, 116)
                                                .addComponent(jTextCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)))
                        .addComponent(jbEliminarCiu)
                        .addGap(92, 92, 92)
                        .addComponent(jbSalirCiu)
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonEstadoCiudad)
                    .addComponent(jLabel5))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarCiu)
                    .addComponent(jbModificarCiu)
                    .addComponent(jbEliminarCiu)
                    .addComponent(jbSalirCiu)
                    .addComponent(jbLimpiarCiu))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ciudades", jPanel2);

        jtAlojamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ciudad", "Tipo", "Costo Diario", "Servicios"
            }
        ));
        jScrollPane2.setViewportView(jtAlojamientos);

        jLabel6.setText("Ciudad:");

        jLabel7.setText("Tipo:");

        jLabel8.setText("Costo:");

        jLabel9.setText("Servicio:");

        jTextCiudadAlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCiudadAloActionPerformed(evt);
            }
        });
        jTextCiudadAlo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCiudadAloKeyTyped(evt);
            }
        });

        jTextTipoAlo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTipoAloKeyTyped(evt);
            }
        });

        jTextCostoAlo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCostoAloKeyTyped(evt);
            }
        });

        jTextServicioAlo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextServicioAloKeyTyped(evt);
            }
        });

        jbAgregarAlo.setText("Agregar");
        jbAgregarAlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarAloActionPerformed(evt);
            }
        });

        jbModificarAlo.setText("Modificar");
        jbModificarAlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarAloActionPerformed(evt);
            }
        });

        jbEliminarAlo.setText("Eliminar");
        jbEliminarAlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarAloActionPerformed(evt);
            }
        });

        jbSalirAlo.setText("Salir");
        jbSalirAlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirAloActionPerformed(evt);
            }
        });

        jbLimpiarAlo.setText("Limpiar");
        jbLimpiarAlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarAloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCiudadAlo)
                            .addComponent(jTextTipoAlo)
                            .addComponent(jTextCostoAlo)
                            .addComponent(jTextServicioAlo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jbLimpiarAlo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(jbAgregarAlo)
                        .addGap(118, 118, 118)
                        .addComponent(jbModificarAlo)
                        .addGap(107, 107, 107)))
                .addComponent(jbEliminarAlo)
                .addGap(100, 100, 100)
                .addComponent(jbSalirAlo)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextCiudadAlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextTipoAlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextCostoAlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextServicioAlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarAlo)
                    .addComponent(jbModificarAlo)
                    .addComponent(jbEliminarAlo)
                    .addComponent(jbSalirAlo)
                    .addComponent(jbLimpiarAlo))
                .addGap(80, 80, 80))
        );

        jTabbedPane1.addTab("Alojamientos", jPanel3);

        jtTransportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Transporte", "Precio", "Ciudad de Origen"
            }
        ));
        jScrollPane3.setViewportView(jtTransportes);

        jLabel10.setText("Tipo de Transporte:");

        jLabel11.setText("Precio:");

        jLabel12.setText("Ciudad de Origen:");

        jTextTipoTransp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTipoTranspKeyTyped(evt);
            }
        });

        jTextPrecioTransp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPrecioTranspKeyTyped(evt);
            }
        });

        jTextCiudadOrigenTransp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCiudadOrigenTranspKeyTyped(evt);
            }
        });

        jbAgregarTran.setText("Agregar");
        jbAgregarTran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarTranActionPerformed(evt);
            }
        });

        jbModificarTran.setText("Modificar");
        jbModificarTran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarTranActionPerformed(evt);
            }
        });

        jbEliminarTran.setText("Eliminar");
        jbEliminarTran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarTranActionPerformed(evt);
            }
        });

        jbSalirTran.setText("Salir");
        jbSalirTran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirTranActionPerformed(evt);
            }
        });

        jbLimpiarTran.setText("Limpiar");
        jbLimpiarTran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarTranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextTipoTransp)
                            .addComponent(jTextPrecioTransp)
                            .addComponent(jTextCiudadOrigenTransp, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbLimpiarTran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jbAgregarTran)
                        .addGap(101, 101, 101)
                        .addComponent(jbModificarTran)
                        .addGap(134, 134, 134)))
                .addComponent(jbEliminarTran)
                .addGap(94, 94, 94)
                .addComponent(jbSalirTran)
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextTipoTransp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextPrecioTransp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextCiudadOrigenTransp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarTran)
                    .addComponent(jbModificarTran)
                    .addComponent(jbEliminarTran)
                    .addComponent(jbSalirTran)
                    .addComponent(jbLimpiarTran))
                .addGap(75, 75, 75))
        );

        jTabbedPane1.addTab("Transportes", jPanel4);

        jtPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ciudad Origen", "Ciudad Destino", "Alojamiento", "Transporte"
            }
        ));
        jScrollPane4.setViewportView(jtPaquetes);

        jLabel13.setText("Ciudad de Origen:");

        jLabel14.setText("Ciudad de Destino:");

        jLabel15.setText("Alojamiento:");

        jLabel16.setText("Transporte:");

        jTextCiuOrgPaq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCiuOrgPaqKeyTyped(evt);
            }
        });

        jTextCiuDesPaq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCiuDesPaqKeyTyped(evt);
            }
        });

        jTextAlojamientoPaq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAlojamientoPaqKeyTyped(evt);
            }
        });

        jTextTransportePaq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTransportePaqKeyTyped(evt);
            }
        });

        jbAgregarPaq.setText("Agregar");
        jbAgregarPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarPaqActionPerformed(evt);
            }
        });

        jbModificarPaq.setText("Modificar");
        jbModificarPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarPaqActionPerformed(evt);
            }
        });

        jbEliminarPaq.setText("Eliminar");
        jbEliminarPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarPaqActionPerformed(evt);
            }
        });

        jbSalirPaq.setText("Salir");
        jbSalirPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirPaqActionPerformed(evt);
            }
        });

        jbLimpiarPaq.setText("Limpiar");
        jbLimpiarPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarPaqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextTransportePaq, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jTextAlojamientoPaq)
                            .addComponent(jTextCiuDesPaq)
                            .addComponent(jTextCiuOrgPaq))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jbLimpiarPaq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(jbAgregarPaq)
                        .addGap(103, 103, 103)
                        .addComponent(jbModificarPaq)
                        .addGap(98, 98, 98)
                        .addComponent(jbEliminarPaq)
                        .addGap(94, 94, 94)
                        .addComponent(jbSalirPaq)
                        .addGap(38, 38, 38))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextCiuOrgPaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextCiuDesPaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextAlojamientoPaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextTransportePaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarPaq)
                    .addComponent(jbModificarPaq)
                    .addComponent(jbEliminarPaq)
                    .addComponent(jbSalirPaq)
                    .addComponent(jbLimpiarPaq))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paquetes", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPaisActionPerformed

    private void jTextProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProvinciaActionPerformed

    private void jbModificarCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarCiuActionPerformed
        limpiarCiudad();
    }//GEN-LAST:event_jbModificarCiuActionPerformed

    private void jTextCiudadAloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCiudadAloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCiudadAloActionPerformed

    private void jbModificarAloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarAloActionPerformed
        limpiarAlojamiento();
        
    }//GEN-LAST:event_jbModificarAloActionPerformed

    private void jbSalirTranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirTranActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jbSalirTranActionPerformed

    private void jbSalirPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirPaqActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jbSalirPaqActionPerformed

    private void jbSalirCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirCiuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jbSalirCiuActionPerformed

    private void jbSalirAloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirAloActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jbSalirAloActionPerformed

    private void jbAgregarPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarPaqActionPerformed
        limpiarPaquetes();
        
    }//GEN-LAST:event_jbAgregarPaqActionPerformed

    private void jbModificarPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarPaqActionPerformed
        limpiarPaquetes();
    }//GEN-LAST:event_jbModificarPaqActionPerformed

    private void jbEliminarPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarPaqActionPerformed
        limpiarPaquetes();
    }//GEN-LAST:event_jbEliminarPaqActionPerformed

    private void jbAgregarCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarCiuActionPerformed
        //El codigo funciona pero en los campos de string deja poner numeros
        //se puede solucionar?
        
        
        try{
        
        String nombre = jTextCiudad.getText();
        String pais = jTextPais.getText();
        String provincia = jTextProvincia.getText();
        Boolean estado=botonEstadoCiudad.isSelected();
        
        if(nombre.isEmpty()||pais.isEmpty() || provincia.isEmpty() || (estado.booleanValue()==false)){
            JOptionPane.showMessageDialog(this, "No puede haber campos vacios");
            return;
        
        }
        
        
        if(ciudadnew==null){
        
            ciudadnew= new Ciudad(nombre, pais, estado, provincia);
            ciuData.guardarCiudad(ciudadnew);
        }
        //else{
//            materiaActual.setNombre(nombre);
//            materiaActual.setAnio(anio);
//            
//            mateData.modificarMateria(materiaActual);
//        
//        }
        
        }catch(IllegalArgumentException ex){//creo que no es el catch correcto
            //cambio "NumerFormatException" por "IllegalArgumentException"
            //no sale ningun msj
            JOptionPane.showMessageDialog(this, "Los campos solo reciben letras");
        
        }
        cargarCiudades();
        limpiarCiudad();
    }//GEN-LAST:event_jbAgregarCiuActionPerformed

    private void jbEliminarCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarCiuActionPerformed
        limpiarCiudad();
    }//GEN-LAST:event_jbEliminarCiuActionPerformed

    private void jbAgregarAloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarAloActionPerformed
        limpiarAlojamiento();
    }//GEN-LAST:event_jbAgregarAloActionPerformed

    private void jbEliminarAloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarAloActionPerformed
        limpiarAlojamiento();
    }//GEN-LAST:event_jbEliminarAloActionPerformed

    private void jbAgregarTranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarTranActionPerformed
        limpiarTransporte();
    }//GEN-LAST:event_jbAgregarTranActionPerformed

    private void jbModificarTranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarTranActionPerformed
        limpiarTransporte();
    }//GEN-LAST:event_jbModificarTranActionPerformed

    private void jbEliminarTranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarTranActionPerformed
        limpiarTransporte();
    }//GEN-LAST:event_jbEliminarTranActionPerformed

    private void jbLimpiarCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarCiuActionPerformed
        limpiarCiudad();
    }//GEN-LAST:event_jbLimpiarCiuActionPerformed

    private void jbLimpiarAloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarAloActionPerformed
        limpiarAlojamiento();
    }//GEN-LAST:event_jbLimpiarAloActionPerformed

    private void jbLimpiarTranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarTranActionPerformed
        limpiarTransporte();
    }//GEN-LAST:event_jbLimpiarTranActionPerformed

    private void jbLimpiarPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarPaqActionPerformed
        limpiarPaquetes();
    }//GEN-LAST:event_jbLimpiarPaqActionPerformed

    private void jTextCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCiudadActionPerformed

    private void jTextCiudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCiudadKeyPressed
       
    }//GEN-LAST:event_jTextCiudadKeyPressed

    private void jTextCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCiudadKeyTyped
        char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextCiudadKeyTyped

    private void jTextPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPaisKeyTyped
       char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextPaisKeyTyped

    private void jTextProvinciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProvinciaKeyTyped
        char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextProvinciaKeyTyped

    private void jTextCiudadAloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCiudadAloKeyTyped
        char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextCiudadAloKeyTyped

    private void jTextTipoAloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTipoAloKeyTyped
        char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextTipoAloKeyTyped

    private void jTextServicioAloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextServicioAloKeyTyped
        char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextServicioAloKeyTyped

    private void jTextCostoAloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCostoAloKeyTyped
        char c = evt.getKeyChar();
    if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
        evt.consume(); // Esto consume el evento y evita que el carácter ingresado se muestre en el campo de texto.
    }
    }//GEN-LAST:event_jTextCostoAloKeyTyped

    private void jTextTipoTranspKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTipoTranspKeyTyped
        char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextTipoTranspKeyTyped

    private void jTextPrecioTranspKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPrecioTranspKeyTyped
        char c = evt.getKeyChar();
    if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
        evt.consume(); // Esto consume el evento y evita que el carácter ingresado se muestre en el campo de texto.
    }
    }//GEN-LAST:event_jTextPrecioTranspKeyTyped

    private void jTextCiudadOrigenTranspKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCiudadOrigenTranspKeyTyped
        char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextCiudadOrigenTranspKeyTyped

    private void jTextCiuOrgPaqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCiuOrgPaqKeyTyped
        char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextCiuOrgPaqKeyTyped

    private void jTextCiuDesPaqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCiuDesPaqKeyTyped
        char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextCiuDesPaqKeyTyped

    private void jTextAlojamientoPaqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAlojamientoPaqKeyTyped
        char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextAlojamientoPaqKeyTyped

    private void jTextTransportePaqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTransportePaqKeyTyped
        char c = evt.getKeyChar();
    
    if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
        // Permite letras, espacios en blanco y teclas de control (como borrar).
        
    } else {
        evt.consume();  // Consumir el evento para evitar que se ingresen otros caracteres.
    }
    }//GEN-LAST:event_jTextTransportePaqKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonEstadoCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextAlojamientoPaq;
    private javax.swing.JTextField jTextCiuDesPaq;
    private javax.swing.JTextField jTextCiuOrgPaq;
    private javax.swing.JTextField jTextCiudad;
    private javax.swing.JTextField jTextCiudadAlo;
    private javax.swing.JTextField jTextCiudadOrigenTransp;
    private javax.swing.JTextField jTextCostoAlo;
    private javax.swing.JTextField jTextPais;
    private javax.swing.JTextField jTextPrecioTransp;
    private javax.swing.JTextField jTextProvincia;
    private javax.swing.JTextField jTextServicioAlo;
    private javax.swing.JTextField jTextTipoAlo;
    private javax.swing.JTextField jTextTipoTransp;
    private javax.swing.JTextField jTextTransportePaq;
    private javax.swing.JButton jbAgregarAlo;
    private javax.swing.JButton jbAgregarCiu;
    private javax.swing.JButton jbAgregarPaq;
    private javax.swing.JButton jbAgregarTran;
    private javax.swing.JButton jbEliminarAlo;
    private javax.swing.JButton jbEliminarCiu;
    private javax.swing.JButton jbEliminarPaq;
    private javax.swing.JButton jbEliminarTran;
    private javax.swing.JButton jbLimpiarAlo;
    private javax.swing.JButton jbLimpiarCiu;
    private javax.swing.JButton jbLimpiarPaq;
    private javax.swing.JButton jbLimpiarTran;
    private javax.swing.JButton jbModificarAlo;
    private javax.swing.JButton jbModificarCiu;
    private javax.swing.JButton jbModificarPaq;
    private javax.swing.JButton jbModificarTran;
    private javax.swing.JButton jbSalirAlo;
    private javax.swing.JButton jbSalirCiu;
    private javax.swing.JButton jbSalirPaq;
    private javax.swing.JButton jbSalirTran;
    private javax.swing.JTable jtAlojamientos;
    private javax.swing.JTable jtCiudades;
    private javax.swing.JTable jtPaquetes;
    private javax.swing.JTable jtTransportes;
    // End of variables declaration//GEN-END:variables

    private void armarCabeceraTabla1() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre");
        filaCabecera.add("Pais");
        filaCabecera.add("Provincia");
        filaCabecera.add("Estado");
        for (Object it: filaCabecera){
            modelo1.addColumn(it);
        }
        jtCiudades.setModel(modelo1);
    }

private void armarCabeceraTabla2() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Ciudad");
        filaCabecera.add("Tipo");
        filaCabecera.add("Costo Diario");
        filaCabecera.add("Servicio");
        
        for (Object it: filaCabecera){
            modelo2.addColumn(it);
        }
        jtAlojamientos.setModel(modelo2);
    }
private void armarCabeceraTabla3() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Transporte");
        filaCabecera.add("Precio");
        filaCabecera.add("Ciudad de Origen");
        
        for (Object it: filaCabecera){
            modelo3.addColumn(it);
        }
        jtTransportes.setModel(modelo3);
    }

private void armarCabeceraTabla4() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Ciudad Origen");
        filaCabecera.add("Ciudad Destino");
        filaCabecera.add("Alojamiento");
        filaCabecera.add("Transporte");
        for (Object it: filaCabecera){
            modelo4.addColumn(it);
        }
        jtPaquetes.setModel(modelo4);
    }

    //CARGA TODOS LAS Ciudades
    private void cargarCiudades() {
    DefaultTableModel modelo = (DefaultTableModel) jtCiudades.getModel();
    modelo1.setRowCount(0); // Limpia la tabla antes de agregar nuevos datos
    
    List<Ciudad> ciudades = cData.listarCiudad(); // Obtén la lista de todos los alojamientos disponibles
    
    for (Ciudad c : ciudades) {
        // Accede a los atributos de Alojamiento y agrega una fila a la tabla
        int id= c.getIdCiudad();
        String nombre = c.getNombre();
        String pais = c.getPais();
        String provincia = c.getProvincia();
        Boolean estado = c.isEstado();
        
        modelo1.addRow(new Object[]{id, nombre, pais, provincia, estado});
    }
    }



    //CARGA TODOS LOS ALOJAMIENTOS
    private void cargarAlojamientos() {
    DefaultTableModel modelo = (DefaultTableModel) jtAlojamientos.getModel();
    modelo2.setRowCount(0); // Limpia la tabla antes de agregar nuevos datos
    
    List<Alojamiento> alojamientos = aData.listarAlojamientos(); // Obtén la lista de todos los alojamientos disponibles
    
    for (Alojamiento a : alojamientos) {
        // Accede a los atributos de Alojamiento y agrega una fila a la tabla
        String tipo = a.getTipo();
        String servicio = a.getServicio();
        double precio = a.getImporteDiario();
        Ciudad ciudad = a.getCiudadDest();
        modelo2.addRow(new Object[]{ciudad, tipo, precio,servicio});
    }
    }
    
    //CARGA TODOS LOS Transportes
    private void cargarTransportes() {
    DefaultTableModel modelo = (DefaultTableModel) jtTransportes.getModel();
    modelo3.setRowCount(0); // Limpia la tabla antes de agregar nuevos datos
    
    List<Pasaje> transportes = tData.listarPasajes(); // Obtén la lista de todos los alojamientos disponibles
    
    for (Pasaje a : transportes) {
        // Accede a los atributos de Alojamiento y agrega una fila a la tabla
        String tipo = a.getTipoTransporte();
        double precio = a.getImporte();
        Ciudad ciudadOrigen = a.getNombreCiudadOrigen();
        modelo3.addRow(new Object[]{tipo, precio, ciudadOrigen});
    }
    }
    
    //CARGA TODOS LOS PAQUETES
    private void cargarPaquetes (){
    DefaultTableModel modelo = (DefaultTableModel) jtPaquetes.getModel();
    modelo4.setRowCount(0); // Limpia la tabla antes de agregar nuevos datos
    
    List<Paquete> paquetes = pData.listarPaquetes(); // Obtén la lista de todos los alojamientos disponibles
    
    for (Paquete a : paquetes) {
        // Accede a los atributos de Alojamiento y agrega una fila a la tabla
        
        Ciudad ciudadOrigen = a.getOrigen();
        Ciudad ciudadDestino = a.getDestino();
        Alojamiento alojamiento = a.getAlojamiento();
        Pasaje transporte = a.getPasaje();
        
        
        
        modelo4.addRow(new Object[]{ciudadOrigen, ciudadDestino,alojamiento,transporte});
    }

    }
    
        private void limpiarCiudad() {
        jTextCiudad.setText("");
        jTextPais.setText("");
        jTextProvincia.setText("");
        botonEstadoCiudad.setSelected(false);
    }
        
        private void limpiarAlojamiento() {
        jTextCiudadAlo.setText("");
        jTextTipoAlo.setText("");
        jTextCostoAlo.setText("");
        jTextServicioAlo.setText("");
    }
            
        private void limpiarTransporte() {
        jTextTipoTransp.setText("");
        jTextPrecioTransp.setText("");
        jTextCiudadOrigenTransp.setText("");
    }
                
    private void limpiarPaquetes() {
        jTextCiuOrgPaq.setText("");
        jTextCiuDesPaq.setText("");
        jTextAlojamientoPaq.setText("");
        jTextTransportePaq.setText("");
    }
}
